#server:
#  port: 8087
#  servlet:
#    context-path: '/ead-authuser/'

  config:
    import: 'optional:configserver:'
  cloud:
    config:
      discovery:
        service-id: ead-config-server
      username: admin
      password: admin
